on:
  push:
    branches:
      - albiruni-fetcher
  schedule:
    - cron: '0 8 * * *' # every day at 8am
name: Pull Data and Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 🍞 Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      
      - name: 🔨 Build Project
        run: |
          bun install
          bun run build
          
      - name: 🚧 Scrape
        run: bun src/utils/server/scraper/seed.mjs
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
